spring.application.name=com
spring.data.mongodb.uri=mongodb+srv://shivkumardhakad998119_db_user:jXBPgHOwuc6JavoI@shivmongodb.mueukhe.mongodb.net/springdb?retryWrites=true&w=majority

spring.data.mongodb.database=ecommercedb
spring.data.mongodb.auto-index-creation=true